# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 378c8e3817741d23e9fd810f838ff2dc34f59e647d553a46e9d63386e89c03cc119f81548add540c948308c82948e282535064e09b44df486ce3f0702cf44d2b

test:
  secret_key_base: d64094dbb41dfaeaf2fd21998936343a8ead4fae7d052aa76537f26d1bcf4503187a7c97817a66afd2a067c8098cf8be049ddcb51ca461bfcf7a38605f9915d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
